#!/usr/bin/env bash
emacsclient -e \
  "(let ((qutebrowser-fifo \"$QUTE_FIFO\")
         (qutebrowser-command-backend 'qutebrowser-fifo-send))
     (condition-case nil
         $@
       (t \"\")))" ; true
